# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python\Qtd\menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from zd1 import Ui_zd1 




class Ui_MainWindow(object):



    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 599)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.vkladki = QtWidgets.QTabWidget(self.centralwidget)
        self.vkladki.setGeometry(QtCore.QRect(0, 0, 891, 641))
        self.vkladki.setMinimumSize(QtCore.QSize(0, 641))
        self.vkladki.setMaximumSize(QtCore.QSize(891, 16777215))
        self.vkladki.setObjectName("vkladki")
        self.menu = QtWidgets.QWidget()
        self.menu.setObjectName("menu")
        self.fon = QtWidgets.QLabel(self.menu)
        self.fon.setGeometry(QtCore.QRect(0, 0, 891, 621))
        self.fon.setText("")
        self.fon.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\image.jpg"))
        self.fon.setScaledContents(True)
        self.fon.setObjectName("fon")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.menu)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 655, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))

        
        color=("\n"
"QPushButton{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(214, 46, 46, 255), stop:0.55 rgba(34, 52, 194, 255), stop:0.98 rgba(239, 108, 174, 254), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(255, 255, 255);}""\n" " QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 138, 189, 255), stop:0.55 rgba(72, 35, 235, 255), stop:0.98 rgba(218, 6, 6, 255), stop:1 rgba(0, 0, 0, 0));}")



        green_color=("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(90, 176, 55, 255), stop:0.579545 rgba(248, 115, 114, 255), stop:1 rgba(255, 173, 255, 255));\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 138, 189, 255), stop:0.55 rgba(72, 35, 235, 255), stop:0.98 rgba(218, 6, 6, 255), stop:1 rgba(0, 0, 0, 0));\n"
"}")

        self.pushButton_3.setStyleSheet(color)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("\n"
"QPushButton{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(214, 46, 46, 255), stop:0.55 rgba(34, 52, 194, 255), stop:0.98 rgba(239, 108, 174, 254), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(255, 255, 255);}""\n" " QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 138, 189, 255), stop:0.55 rgba(72, 35, 235, 255), stop:0.98 rgba(218, 6, 6, 255), stop:1 rgba(0, 0, 0, 0));}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("\n"
"QPushButton{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(214, 46, 46, 255), stop:0.55 rgba(34, 52, 194, 255), stop:0.98 rgba(239, 108, 174, 254), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(255, 255, 255);}""\n" " QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 138, 189, 255), stop:0.55 rgba(72, 35, 235, 255), stop:0.98 rgba(218, 6, 6, 255), stop:1 rgba(0, 0, 0, 0));}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("\n"
"QPushButton{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(214, 46, 46, 255), stop:0.55 rgba(34, 52, 194, 255), stop:0.98 rgba(239, 108, 174, 254), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(255, 255, 255);}""\n" " QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 138, 189, 255), stop:0.55 rgba(72, 35, 235, 255), stop:0.98 rgba(218, 6, 6, 255), stop:1 rgba(0, 0, 0, 0));}")
        
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_8 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("\n"
"QPushButton{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(214, 46, 46, 255), stop:0.55 rgba(34, 52, 194, 255), stop:0.98 rgba(239, 108, 174, 254), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(255, 255, 255);}""\n" " QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 138, 189, 255), stop:0.55 rgba(72, 35, 235, 255), stop:0.98 rgba(218, 6, 6, 255), stop:1 rgba(0, 0, 0, 0));}")
        
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout.addWidget(self.pushButton_8)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet(color)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)

        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(color)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(color)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        


        
        self.label_2 = QtWidgets.QLabel(self.menu)
        self.label_2.setGeometry(QtCore.QRect(670, 40, 51, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\icon\\pr_1"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.menu)
        self.label_3.setGeometry(QtCore.QRect(670, 100, 51, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\icon\\pr_2"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.menu)
        self.label_4.setGeometry(QtCore.QRect(670, 170, 51, 51))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\icon\\pr_3"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.menu)
        self.label_5.setGeometry(QtCore.QRect(670, 230, 51, 51))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\icon\\pr_4"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.menu)
        self.label_6.setGeometry(QtCore.QRect(670, 290, 51, 51))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\icon\\pr_5"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.menu)
        self.label_7.setGeometry(QtCore.QRect(670, 350, 51, 51))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\icon\\pr_6"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.menu)
        self.label_8.setGeometry(QtCore.QRect(670, 410, 51, 51))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\icon\\pr_7"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.menu)
        self.label_9.setGeometry(QtCore.QRect(670, 470, 51, 51))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\free-icon-checked-190411.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_18 = QtWidgets.QLabel(self.menu)
        self.label_18.setGeometry(QtCore.QRect(100, 0, 641, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.label_18.setObjectName("label_18")
        self.vkladki.addTab(self.menu, "")
        self.start = QtWidgets.QWidget()
        self.start.setObjectName("start")
        self.fon_start = QtWidgets.QLabel(self.start)
        self.fon_start.setGeometry(QtCore.QRect(-10, -10, 891, 621))
        self.fon_start.setText("")
        self.fon_start.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\image.jpg"))
        self.fon_start.setScaledContents(True)
        self.fon_start.setObjectName("fon_start")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.start)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 655, 501))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_9.setStyleSheet("\n"
"QPushButton{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(214, 46, 46, 255), stop:0.55 rgba(34, 52, 194, 255), stop:0.98 rgba(239, 108, 174, 254), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(255, 255, 255);}""\n" " QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 138, 189, 255), stop:0.55 rgba(72, 35, 235, 255), stop:0.98 rgba(218, 6, 6, 255), stop:1 rgba(0, 0, 0, 0));}")
        
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet(color)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_2.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet(color)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_2.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet(color)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_2.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet(color)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_2.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet(color)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_2.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet(color)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_2.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet(color)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_2.addWidget(self.pushButton_16)
        self.label_10 = QtWidgets.QLabel(self.start)
        self.label_10.setGeometry(QtCore.QRect(670, 350, 51, 51))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\icon\\pr_6"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.start)
        self.label_11.setGeometry(QtCore.QRect(670, 100, 51, 51))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\icon\\pr_2"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.start)
        self.label_12.setGeometry(QtCore.QRect(670, 410, 51, 51))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\icon\\pr_7"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.start)
        self.label_13.setGeometry(QtCore.QRect(670, 290, 51, 51))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\icon\\pr_5"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.start)
        self.label_14.setGeometry(QtCore.QRect(670, 170, 51, 51))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\icon\\pr_3"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.start)
        self.label_15.setGeometry(QtCore.QRect(670, 470, 51, 51))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("D:\\python\\Qtd\\free-icon-checked-190411.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        


        

        self.label_16 = QtWidgets.QLabel(self.start)
        self.label_16.setGeometry(QtCore.QRect(670, 40, 51, 51))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\icon\\pr_1"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")

        


        #labe16
        self.label_17 = QtWidgets.QLabel(self.start)
        self.label_17.setGeometry(QtCore.QRect(670, 230, 51, 51))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\icon\\pr_4"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label = QtWidgets.QLabel(self.start)
        self.label.setGeometry(QtCore.QRect(200, 0, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.vkladki.addTab(self.start, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.vkladki.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Изучение Питона"))
        self.pushButton_3.setText(_translate("MainWindow", "Использование командной строки интерпретатора "))
        self.pushButton_6.setText(_translate("MainWindow", "Типы данных"))
        self.pushButton_7.setText(_translate("MainWindow", "Операторы\n"
""))
        self.pushButton_5.setText(_translate("MainWindow", "Выражения"))
        self.pushButton_8.setText(_translate("MainWindow", "Цикл for и оператор while"))
        self.pushButton_4.setText(_translate("MainWindow", "Оператор from … import"))
        self.pushButton_2.setText(_translate("MainWindow", "Кортеж"))
        self.pushButton.setText(_translate("MainWindow", "Try .. Finally "))
        self.label_18.setText(_translate("MainWindow", "Перед выполнением заданий рекомендуем ознакомится с темами"))
        self.vkladki.setTabText(self.vkladki.indexOf(self.menu), _translate("MainWindow", "Меню"))
        self.pushButton_9.setText(_translate("MainWindow", "Использование командной строки интерпретатора "))
        self.pushButton_10.setText(_translate("MainWindow", "Типы данных"))
        self.pushButton_11.setText(_translate("MainWindow", "Операторы\n"
""))
        self.pushButton_12.setText(_translate("MainWindow", "Выражения"))
        self.pushButton_13.setText(_translate("MainWindow", "Цикл for и оператор while"))
        self.pushButton_14.setText(_translate("MainWindow", "Оператор from … import"))
        self.pushButton_15.setText(_translate("MainWindow", "Кортеж"))
        self.pushButton_16.setText(_translate("MainWindow", "Try .. Finally "))
        self.label.setText(_translate("MainWindow", "Реши все задания для закрепления темы!"))
        self.vkladki.setTabText(self.vkladki.indexOf(self.start), _translate("MainWindow", "Задания"))



