# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\QT\pr_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pr_2(object):
    def setupUi(self, pr_2):
        pr_2.setObjectName("pr_2")
        pr_2.resize(880, 654)
        self.label = QtWidgets.QLabel(pr_2)
        self.label.setGeometry(QtCore.QRect(0, 0, 881, 651))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\image.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(pr_2)
        self.label_2.setGeometry(QtCore.QRect(330, -20, 351, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(pr_2)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 851, 431))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\2 тема .png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(pr_2)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 841, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setMouseTracking(False)
        self.label_4.setTabletTracking(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(pr_2)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 631, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(pr_2)
        self.pushButton_2.setGeometry(QtCore.QRect(660, 590, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(pr_2)
        QtCore.QMetaObject.connectSlotsByName(pr_2)

    def retranslateUi(self, pr_2):
        _translate = QtCore.QCoreApplication.translate
        pr_2.setWindowTitle(_translate("pr_2", "Изучение Питона"))
        self.label_2.setText(_translate("pr_2", "Типы данных"))
        self.label_4.setText(_translate("pr_2", "Переменные могут хранить значения разных типов, называемых типами данных. "))
        self.label_5.setText(_translate("pr_2", "основными типами являются числа и строки"))
        self.pushButton_2.setText(_translate("pr_2", "Выход"))


        
