# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\QT\pr_3(1).ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pr_3_1(object):
    def setupUi(self, pr_3_1):
        pr_3_1.setObjectName("pr_3_1")
        pr_3_1.resize(929, 711)
        self.label = QtWidgets.QLabel(pr_3_1)
        self.label.setGeometry(QtCore.QRect(0, 0, 931, 711))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\icon/Pr_3/pr_3_1.PNG"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(pr_3_1)
        self.pushButton.setGeometry(QtCore.QRect(660, 650, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(pr_3_1)
        QtCore.QMetaObject.connectSlotsByName(pr_3_1)

    def retranslateUi(self, pr_3_1):
        _translate = QtCore.QCoreApplication.translate
        pr_3_1.setWindowTitle(_translate("pr_3_1", "Изучение Питона"))
        self.pushButton.setText(_translate("pr_3_1", "Далее"))


