# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\QT\pr_7.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pr_7(object):
    def setupUi(self, pr_7):
        pr_7.setObjectName("pr_7")
        pr_7.resize(880, 757)
        self.label = QtWidgets.QLabel(pr_7)
        self.label.setGeometry(QtCore.QRect(0, 0, 881, 651))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\image.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(pr_7)
        self.label_2.setGeometry(QtCore.QRect(350, -30, 351, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(pr_7)
        self.pushButton_2.setGeometry(QtCore.QRect(740, 560, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(pr_7)
        self.label_3.setGeometry(QtCore.QRect(130, 40, 611, 681))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\7 тема.PNG"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(pr_7)
        self.label_4.setGeometry(QtCore.QRect(0, 120, 881, 651))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\image.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton_2.raise_()
        self.label_3.raise_()

        self.retranslateUi(pr_7)
        QtCore.QMetaObject.connectSlotsByName(pr_7)

    def retranslateUi(self, pr_7):
        _translate = QtCore.QCoreApplication.translate
        pr_7.setWindowTitle(_translate("pr_7", "Изучение Питона"))
        self.label_2.setText(_translate("pr_7", "Кортеж"))
        self.pushButton_2.setText(_translate("pr_7", "OK"))


