# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_start(object):
    def setupUi(self, start):
        start.setObjectName("start")
        start.resize(675, 436)
        self.buttonBox = QtWidgets.QDialogButtonBox(start)
        self.buttonBox.setGeometry(QtCore.QRect(330, 400, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_2 = QtWidgets.QLabel(start)
        self.label_2.setGeometry(QtCore.QRect(150, -10, 351, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("python.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(start)
        self.label.setGeometry(QtCore.QRect(0, 0, 681, 441))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("start(1).jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(start)
        self.label_3.setGeometry(QtCore.QRect(100, 130, 661, 91))
        self.label_3.setMaximumSize(QtCore.QSize(661, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setMouseTracking(False)
        self.label_3.setTabletTracking(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(start)
        self.label_4.setGeometry(QtCore.QRect(120, 180, 601, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(start)
        self.label_5.setGeometry(QtCore.QRect(190, 240, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(start)
        self.label_6.setGeometry(QtCore.QRect(130, 290, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label.raise_()
        self.label_2.raise_()
        self.buttonBox.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()

        self.retranslateUi(start)
        self.buttonBox.accepted.connect(start.accept) # type: ignore
        self.buttonBox.rejected.connect(start.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(start)

    def retranslateUi(self, start):
        _translate = QtCore.QCoreApplication.translate
        start.setWindowTitle(_translate("start", "Изучение питона"))
        self.label_3.setText(_translate("start", "Здравствуйте,это приложение по изучению питона"))
        self.label_4.setText(_translate("start", "вам предстоит ознакомиться с теоритическим "))
        self.label_5.setText(_translate("start", "материалом и решить задания"))
        self.label_6.setText(_translate("start", "P.S: не закрывайте окна,для выхода из заданий нажимайте \"OK\""))


