# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\QT\start_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_start(object):
    def setupUi(self, start):
        start.setObjectName("start")
        start.resize(675, 407)
        self.buttonBox = QtWidgets.QDialogButtonBox(start)
        self.buttonBox.setGeometry(QtCore.QRect(330, 370, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(start)
        self.label.setGeometry(QtCore.QRect(0, 0, 681, 441))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\icon/start.PNG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.buttonBox.raise_()

        self.retranslateUi(start)
        self.buttonBox.accepted.connect(start.accept) # type: ignore
        self.buttonBox.rejected.connect(start.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(start)

    def retranslateUi(self, start):
        _translate = QtCore.QCoreApplication.translate
        start.setWindowTitle(_translate("start", "Изучение питона"))


