# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python\Qtd\tem1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):

        Form.setObjectName("Form")
        Form.resize(839, 621)
        self.fon = QtWidgets.QLabel(Form)
        self.fon.setGeometry(QtCore.QRect(0, 0, 891, 621))
        self.fon.setText("")
        self.fon.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\image.jpg"))
        self.fon.setScaledContents(True)
        self.fon.setObjectName("fon")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 20, 651, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 60, 831, 521))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\1 тема.PNG"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.ok = QtWidgets.QDialogButtonBox(Form)
        self.ok.setGeometry(QtCore.QRect(280, 590, 221, 23))
        self.ok.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ok.setObjectName("ok")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Изучение Питона"))
        self.label.setText(_translate("Form", "Использование командной строки интерпретатора "))


