# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python\Qtd\zd1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import time




class Ui_zd1(object):
    
        
    
    def setupUi(self, zd1):
        zd1.setObjectName("zd1")
        zd1.resize(843, 597)
        self.fon_start = QtWidgets.QLabel(zd1)
        self.fon_start.setGeometry(QtCore.QRect(-50, -10, 891, 621))
        self.fon_start.setText("")
        self.fon_start.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\image.jpg"))
        self.fon_start.setScaledContents(True)
        self.fon_start.setObjectName("fon_start")
        self.label = QtWidgets.QLabel(zd1)
        self.label.setGeometry(QtCore.QRect(120, -10, 611, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(zd1)
        self.lineEdit.setGeometry(QtCore.QRect(240, 160, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(zd1)
        self.pushButton.setGeometry(QtCore.QRect(270, 280, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(zd1)
        self.label_2.setGeometry(QtCore.QRect(310, 400, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(111, 255, 89);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(zd1)
        self.label_3.setGeometry(QtCore.QRect(290, 390, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(170, 0, 0)")
        self.label_3.setObjectName("label_3")

        self.ok = QtWidgets.QDialogButtonBox(zd1)
        self.ok.setGeometry(QtCore.QRect(280, 566, 221, 23))
        self.ok.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ok.setObjectName("ok")
    
        


        self.retranslateUi(zd1)
        QtCore.QMetaObject.connectSlotsByName(zd1)


    



    def retranslateUi(self, zd1):
        _translate = QtCore.QCoreApplication.translate
        zd1.setWindowTitle(_translate("zd1", "Изучение Питона"))
        self.label.setText(_translate("zd1", "Как написать первую программу \"Hello World\"?"))
        self.pushButton.setText(_translate("zd1", "Проверить!"))
        
        

        def ed():
            global g
            g = self.lineEdit.text()
            if g=='print("Hello World")':
                
                self.label_2.setText(_translate("zd1", "Все верно!"))
                self.label_3.deleteLater()



            else:
                 
                self.label_3.setText(_translate("zd1", "Подумай ещё!"))
     


        self.pushButton.clicked.connect(ed)
    
    





