# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\QT\zd2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_zd_4(object):
    def setupUi(self, zd_4):
        zd_4.setObjectName("zd_4")
        zd_4.resize(930, 710)
        self.label = QtWidgets.QLabel(zd_4)
        self.label.setGeometry(QtCore.QRect(0, 0, 931, 711))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\image.jpg"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(zd_4)
        self.label_2.setGeometry(QtCore.QRect(350, 0, 301, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(zd_4)
        self.pushButton.setGeometry(QtCore.QRect(280, 620, 281, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(zd_4)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 871, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(zd_4)
        self.lineEdit.setGeometry(QtCore.QRect(110, 200, 651, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(zd_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 320, 651, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(zd_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 440, 651, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(zd_4)
        self.label_5.setGeometry(QtCore.QRect(110, 130, 651, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(zd_4)
        self.label_6.setGeometry(QtCore.QRect(110, 250, 611, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(zd_4)
        self.label_7.setGeometry(QtCore.QRect(50, 370, 861, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(zd_4)
        self.label_9.setGeometry(QtCore.QRect(600, 630, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(111, 255, 89);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(zd_4)
        self.label_10.setGeometry(QtCore.QRect(570, 620, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 21, 24);\n"
"background-color: rgb(100, 96, 92);")
        self.label_10.setObjectName("label_10")
        self.pushButton_2 = QtWidgets.QPushButton(zd_4)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 620, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(zd_4)
        QtCore.QMetaObject.connectSlotsByName(zd_4)

    def retranslateUi(self, zd_4):
        _translate = QtCore.QCoreApplication.translate
        zd_4.setWindowTitle(_translate("zd_4", "Изучение Питона"))
        self.label_2.setText(_translate("zd_4", "Типы данных"))
        self.pushButton.setText(_translate("zd_4", "Проверить"))
        self.label_3.setText(_translate("zd_4", "Ответьте на вопросы:"))
        self.label_5.setText(_translate("zd_4", "К какому типу данных относятся числа: 1.2; 4.657; 124.755; 0.95?"))
        self.label_6.setText(_translate("zd_4", "К какому типу данных относятся слова:\"hello world\", \"drive\""))
        self.label_7.setText(_translate("zd_4", "К какому типу данных относятся переменные записанные в такой форме:{\"a\",\"c\",\"g\"}"))

        self.pushButton_2.setText(_translate("zd_4", "Выход"))

        def ed():
            global g
            g = self.lineEdit.text()
            if g=='float':
                h=self.lineEdit_2.text()
                if h=='str':
                    f=self.lineEdit_3.text()
                    if f=='set':
                        self.label_9.setText(_translate("zd1", "Все верно!"))
                        self.label_10.deleteLater()
                    

                    elif f=='':
                        self.label_10.setText(_translate("zd1", "Заполни до конца!"))
                    else:
                        self.label_10.setText(_translate("zd1", "Подумай ещё!"))



                elif h=='':
                    self.label_10.setText(_translate("zd1", "Заполни до конца!"))
                else:
                    self.label_10.setText(_translate("zd1", "Подумай ещё!"))



            elif g=='':
                 
                self.label_10.setText(_translate("zd1", "Заполни до конца!"))
            else:
                self.label_10.setText(_translate("zd1", "Подумай ещё!"))
     


        self.pushButton.clicked.connect(ed)
    