# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\QT\zd5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random
import os

class Ui_zd_5(object):
    def setupUi(self, zd_5):
        zd_5.setObjectName("zd_5")
        zd_5.resize(880, 646)
        self.label = QtWidgets.QLabel(zd_5)
        self.label.setGeometry(QtCore.QRect(0, 0, 881, 651))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\image.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(zd_5)
        self.label_2.setGeometry(QtCore.QRect(290, -30, 351, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(zd_5)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 600, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(zd_5)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 600, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(zd_5)
        self.label_3.setGeometry(QtCore.QRect(50, 10, 801, 171))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(zd_5)
        self.label_4.setGeometry(QtCore.QRect(80, 90, 781, 121))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(zd_5)
        self.plainTextEdit.setGeometry(QtCore.QRect(160, 190, 561, 161))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_5 = QtWidgets.QLabel(zd_5)
        self.label_5.setGeometry(QtCore.QRect(350, 360, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(66, 198, 0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(zd_5)
        self.label_6.setGeometry(QtCore.QRect(0, 450, 561, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(66, 198, 0);")
        self.label_6.setObjectName("label_6")
        self.a_text = QtWidgets.QLabel(zd_5)
        self.a_text.setGeometry(QtCore.QRect(280, 440, 591, 81))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.a_text.setFont(font)
        self.a_text.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.a_text.setMouseTracking(False)
        self.a_text.setStyleSheet("\n"
"background-color: rgb(0, 0, 255);\n"
"background-color: rgb(224, 241, 255);\n"
"color: rgb(85, 42, 14);\n"
"")
        self.a_text.setObjectName("a_text")
        self.label_7 = QtWidgets.QLabel(zd_5)
        self.label_7.setGeometry(QtCore.QRect(320, 360, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(157, 0, 0);\n"
"")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(zd_5)
        QtCore.QMetaObject.connectSlotsByName(zd_5)

    def retranslateUi(self, zd_5):
        _translate = QtCore.QCoreApplication.translate
        zd_5.setWindowTitle(_translate("zd_5", "Изучение Питона"))
        self.label_2.setText(_translate("zd_5", "Цикл for и оператор while"))
        self.pushButton_2.setText(_translate("zd_5", "Проверить"))
        self.pushButton_3.setText(_translate("zd_5", "Выход"))
        self.label_3.setText(_translate("zd_5", "Напишите программу которая генерировала бы 10 рандомных чисел."))
        self.label_4.setText(_translate("zd_5", "если команда рандомного числа выглядит так: \"random.randint(1,500)\""))
        
        
        
        


        def ed():
            try:

                global g
                g=self.plainTextEdit.toPlainText()
                result=[]
                try:
                    first_line = g.split('\n')[0]
                    line=g.split('\n')[1]
                except IndexError:
                    self.label_7.setText(_translate("zd_5", "Подумай ещё!"))
                finally:

                    try:
                        if first_line=='for i in range(1,11):':
                            if line== 'i=random.randint(1,500)':
                                for i in range(1,11):
                                    i=random.randint(1,500)
                                    result.append(i)
                        
                                self.label_5.setText(_translate("zd_5", "Все верно!"))
                                self.label_6.setText(_translate("zd_5", "Получились значения:"))
                                self.a_text.setText(_translate("zd_5",f"{result}"))
                                self.label_7.deleteLater()

                        else:
                            
                            self.label_7.setText(_translate("zd_5", "Подумай ещё!"))
                    except UnboundLocalError:
                        pass
            except RuntimeError:
                pass


        self.pushButton_2.clicked.connect(ed)

#
#'for i in range(1,11):i=random.randint(1,500);print(i)'