# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\QT\zd7.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_zd_7(object):
    def setupUi(self, zd_7):
        zd_7.setObjectName("zd_7")
        zd_7.resize(880, 646)
        self.label = QtWidgets.QLabel(zd_7)
        self.label.setGeometry(QtCore.QRect(0, 0, 881, 651))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Python\\QT\\image.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(zd_7)
        self.label_2.setGeometry(QtCore.QRect(350, -20, 351, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(zd_7)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 600, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(zd_7)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 600, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(zd_7)
        self.label_3.setGeometry(QtCore.QRect(50, 60, 821, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(zd_7)
        self.label_5.setGeometry(QtCore.QRect(310, 530, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(66, 198, 0);")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(zd_7)
        self.label_7.setGeometry(QtCore.QRect(310, 530, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(157, 0, 0);\n"
"")
        self.label_7.setObjectName("label_7")
        self.radioButton = QtWidgets.QRadioButton(zd_7)
        self.radioButton.setGeometry(QtCore.QRect(50, 160, 721, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(zd_7)
        self.radioButton_2.setGeometry(QtCore.QRect(50, 230, 731, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(zd_7)
        self.radioButton_3.setGeometry(QtCore.QRect(50, 290, 661, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(zd_7)
        self.radioButton_4.setGeometry(QtCore.QRect(50, 360, 661, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_4.setObjectName("radioButton_4")

        self.retranslateUi(zd_7)
        QtCore.QMetaObject.connectSlotsByName(zd_7)

    def retranslateUi(self, zd_7):
        _translate = QtCore.QCoreApplication.translate
        zd_7.setWindowTitle(_translate("zd_7", "Изучение Питона"))
        self.label_2.setText(_translate("zd_7", "Кортеж"))
        self.pushButton_2.setText(_translate("zd_7", "Проверить"))
        self.pushButton_3.setText(_translate("zd_7", "Выход"))
        self.label_3.setText(_translate("zd_7", "Как добавить в новую переменную старые и новые записи в кортеже?"))

        self.radioButton.setText(_translate("zd_7", "Переменная=\'запись\',\'запись\',старый кортеж"))
        self.radioButton_2.setText(_translate("zd_7", "Переменная.append(cтарый кортеж)"))
        self.radioButton_3.setText(_translate("zd_7", "Переменная=запись;запись;старый кортеж;"))
        self.radioButton_4.setText(_translate("zd_7", "Переменная=+запись ,+запись,+старый кортеж,"))


        def ed():
            try:
                if self.radioButton.isChecked():
                    self.label_5.setText(_translate("zd_8", "Все верно!"))
                    try:
                        self.label_7.deleteLater()
                    except RuntimeError:
                        pass
                elif self.radioButton_2.isChecked():
                    self.label_7.setText(_translate("zd_8", "Подумай ещё!"))
                    try:
                        self.label_5.deleteLater()
                    except RuntimeError:
                        pass
                    
                elif self.radioButton_3.isChecked():
                    self.label_7.setText(_translate("zd_8", "Подумай ещё!"))
                    
                    try:
                        self.label_5.deleteLater()
                    except RuntimeError:
                        pass
            except RuntimeError:
                pass
        self.pushButton_2.clicked.connect(ed)
